name: journaly
description: "Random journal app"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

isar_version: &isar_version 3.1.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive: any
  hive_flutter: any
  loading_animation_widget: ^1.2.0+4
  http: ^1.2.0
  google_fonts: ^6.2.0
  skeletonizer: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
