version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: random
    restart: always
    environment:
      POSTGRES_DB: random
      POSTGRES_USER: jumba
      POSTGRES_PASSWORD: random
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres-data:
